create database customer_behavior;
use customer_behavior;
select * from customer;

--  Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as total_revenue
from customer
group by gender;

--  Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id from 
customer
 where discount_applied = "yes" and purchase_amount >= (select avg(purchase_amount) from customer);

--  Q3. Which are the top 5 products with the highest average review rating?

with cte as
(select item_purchased as products,
avg(review_rating) as avg_rating,
row_number() over(order by avg(review_rating) desc) as rk
from customer
group by item_purchased)
select * from cte
where rk <= 5;

--  Q.4 Compare the average purchase Amounts between Standard and Express Shipping.

select shipping_type,
avg(purchase_amount) avg_purchase_amount
from customer
where shipping_type in ("Standard","Express")
group by shipping_type;

--  Q.5 Do Subscribed Customers spend more? Compare average Spend and total revenue between subscribers and non-subscribers.

select subscription_status,
sum(purchase_amount) as total_revenue,
avg(purchase_amount) as average_spend,
count(customer_id) as total_customer
from customer
group by subscription_status;

--  Q.6 Which 5 Products have the highest percentage of purchases with discounts applied?

select item_purchased,
ROUND(100 * sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5; 

--  Q.7 Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

with cte as
(
select customer_id,previous_purchases,
case 
   when previous_purchases = 1 then "New"
   when previous_purchases between 2 and 10 then "Returning"
   else "Loyal" end as customer_segment
   from customer)
   select customer_segment,count(*) as total_customers
   from cte
   group by customer_segment;

--  Q.8 What are the top 3 most purchased products within each category?

with cte as
(select category,
item_purchased,
count(customer_id) as total_customer,
row_number() over(partition by category order by count(customer_id) desc) as rk
from customer
group by category,item_purchased)
select rk,category,total_customer,item_purchased
from cte 
where rk <=3;


--  Q.9 Are customers who are repeat buyers (more than 5 previous purchases) also likely subscribe?

select subscription_status,
count(customer_id) as total_customer
from customer
where previous_purchases > 5
group by subscription_status;

--  Q.10 what is the revenue contribution of age group? 

select age_group,sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;